name: snort
services:
    snort:
        restart: always
        cap_add:
            - NET_ADMIN
        build:
            dockerfile: Dockerfile
            context: ./
        volumes:
            - ./snort-conf:/usr/local/etc/snort
            - ./snort.rules:/usr/local/etc/rules/local.rules
            - ./logs:/var/log/snort
        networks:
            snort_lan:
            
networks:
    snort_lan:
        driver: bridge