name: snort
services:
    snort:
        restart: always
        build:
            dockerfile: Dockerfile
            context: ./
        volumes:
            - ./snort-conf:/usr/local/etc/snort
            - ./snort-rules.txt:/usr/local/etc/rules/local.rules
        ports:
            - 22:22
        networks:
            snort_lan:
    ping:
        image: willfarrell/ping
        environment:
            HOSTNAME: snort
            TIMEOUT: 10
        networks:
            snort_lan:
networks:
    snort_lan:
        driver: bridge
#volumes:
#    snort: